site_name: SuchTree Documentation
theme:
  name: material
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

repo_url: https://github.com/ryneches/suchtree
repo_name: GitHub

nav:
  - Home: index.md
  - Working Example: examples/SuchTree_examples.md
  - Linked Trees: examples/SuchLinkedTree_examples.md
  - Example Datasets: datasets.md
  - Release Notes: release_notes.md
  - Publication: paper.md
  - Benchmarks: benchmarks.md
  - API: SuchTree_API.md
  - API Reference: api.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
- mkdocstrings:
    handlers:
      python:
        options-extra:
          import:
            - https://docs.python.org/3/objects.inv
          show_root_heading: true
          show_source: false
          show_source_link: true
          source_link_template: "https://github.com/ryneches/suchtree/blob/main/{path}#L{line}"
          import_cython: true
