site_name: SuchTree Documentation
theme:
  name: material
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

repo_url: https://github.com/ryneches/suchtree
repo_name: GitHub

nav:
  - Home: index.md
  - Working Example: examples/SuchTree_examples.md
  - Linked Trees: examples/SuchLinkedTree_examples.md
  - Example Datasets: datasets.md
  - Release Notes: release_notes.md
  - Publication: paper.md
  - Benchmarks: benchmarks.md
  - API: SuchTree_API.md
  - API Reference: api.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          inventories:
            - https://docs.python.org/3/objects.inv
          options:
            show_signature_annotations: true
            show_source: false
            group_by_category: true
            show_root_heading: false
            members_order: source
            docstring_style: google
            docstring_section_style: table
            merge_init_into_class: true
            show_if_no_docstring: false
