name: Build package

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  pull_request:
    branches: [ "main" ]

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    outputs:
      SDIST_NAME: ${{ steps.sdist.outputs.SDIST_NAME }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # setuptools-scm auto versioning needs tags
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install build and test dependencies
        run: |
          python -m pip install packaging build twine flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install -e .
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 SuchTree --count --ignore=E201,E202,E203 \
          --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 SuchTree --count --ignore=E201,E202,E203 \
          --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: pytest
      - name: Build source distribution
        id: sdist
        run: |
          python -m build --sdist
          python .github/export_sdist_name.py
      - name: Upload sdist result
        uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
          if-no-files-found: error
  
  build_wheels:
    name: Build wheels on ${{ matrix.os }} for ${{ matrix.cibw_archs }}
    needs: build_sdist
    runs-on: ${{ matrix.os }}
    env:
      CIBW_BEFORE_BUILD: >-
        rm -rf {package}/build
      CIBW_BEFORE_BUILD_WINDOWS: >-
        pip install delvewheel &&
        rm -rf {package}/build
      CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: >-
        delvewheel repair -w {dest_dir} {wheel}
      CIBW_AFTER_BUILD: >-
        twine check {wheel}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cibw_archs: "x86_64"
          - os: ubuntu-latest
            cibw_archs: "aarch64"
          - os: windows-latest
            cibw_archs: "auto64"
          - os: macos-latest
            cibw_archs: "x86_64"
          - os: macos-latest
            cibw_archs: "arm64"
    steps:
      - name: Download sdist
        uses: actions/download-artifact@v4
        with:
          name: cibw-sdist
          path: dist/
      
      - name: Set up QEMU
        if: matrix.cibw_archs == 'aarch64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      
      - name: Build wheels for CPython 3.13
        uses: pypa/cibuildwheel@v3.1.4
        with:
          package-dir: dist/${{ needs.build_sdist.outputs.SDIST_NAME }}
        env:
          CIBW_BUILD: "cp313-*"
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
      
      - name: Build wheels for CPython 3.12
        uses: pypa/cibuildwheel@v3.1.4
        with:
          package-dir: dist/${{ needs.build_sdist.outputs.SDIST_NAME }}
        env:
          CIBW_BUILD: "cp312-*"
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
      
      - name: Build wheels for CPython 3.11
        uses: pypa/cibuildwheel@v3.1.4
        with:
          package-dir: dist/${{ needs.build_sdist.outputs.SDIST_NAME }}
        env:
          CIBW_BUILD: "cp311-*"
          CIBW_ARCHS: ${{ matrix.cibw_archs }}

      - name: Build wheels for CPython 3.10
        uses: pypa/cibuildwheel@v3.1.4
        with:
          package-dir: dist/${{ needs.build_sdist.outputs.SDIST_NAME }}
        env:
          CIBW_BUILD: "cp310-*"
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
      
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ runner.os }}-${{ matrix.cibw_archs }}
          path: ./wheelhouse/*.whl

  merge:
    name: Merge Artifacts
    runs-on: ubuntu-latest
    needs: build_wheels
    steps:
      - name: Merge wheel artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: cibw-wheels
          pattern: cibw-wheels-*
      
      - name: Download sdist
        uses: actions/download-artifact@v4
        with:
          name: cibw-sdist
          path: dist-sdist/
      
      - name: Download merged wheels
        uses: actions/download-artifact@v4
        with:
          name: cibw-wheels
          path: dist-wheels/
      
      - name: Combine sdist and wheels
        run: |
          mkdir -p dist
          cp dist-sdist/*.tar.gz dist/
          cp dist-wheels/*.whl dist/
          ls -lh dist/
      
      - name: Upload combined release distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    name: Publish to PyPI
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: merge
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    
    environment:
      name: pypi
      url: https://pypi.org/p/SuchTree
    
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
