name: Build wheels

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} for python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]
        os: [ ubuntu-latest, macOS-latest ]
        exclude:
          - os: macOS-latest
            python-version: "3.12"
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with :
          python-version: ${{ matrix.python-version }}
      
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      
      - name: Install test dependencies
        run: |
          python -m pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install -e .
      
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 SuchTree --count --ignore=E201,E202,E203 --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 SuchTree --count --ignore=E201,E202,E203 --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Test with pytest
        run: pytest
      
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.18.0
      
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
      
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  merge:
    runs-on: ubuntu-latest
    needs: build_wheels
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: wheelhouse
          pattern: cibw-wheels-*
